#
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- include: _write_conf.yml
  src: "../templates/cassandra.yaml.j2"
  dest: "{{ cassandra_conf_dir }}/cassandra.yaml"
  when: ansible_os_family == "Suse"

- include: _write_conf.yml
  src: "../templates/jvm.options.j2"
  dest: "{{ cassandra_conf_dir }}/jvm.options"
  when: ansible_os_family == "Suse"

- include: _write_conf.yml
  src: "../templates/cassandra-rackdc.properties.j2"
  dest: "{{ cassandra_conf_dir }}/cassandra-rackdc.properties"
  when: ansible_os_family == "Suse"

# TODO(ashwin): figure out how to do this
# - name: FND-CDB | configure | Register cassandra restart
#   command: /bin/true
#   register: hlm_notify_cassandra_restart_required
#   when: hlm_notify_cassandra_restart_required.changed

- name: FND-CDB | configure | configure cassandra log file ownership
  become: yes
  file:
    path: "{{ cassandra_log_dir }}/{{ item }}"
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    mode: 0640
    state: touch
  with_items:
    - debug.log
    - gc.log.0.current
    - system.log
    - cassandra.log
  when: ansible_os_family == "Suse"

- name: FND-CDB | configure | set cassandra log file ownership
  become: yes
  file:
    path: "{{ cassandra_log_dir }}/{{ item }}"
    state: touch
    owner: "{{ cassandra_user }}"
    group: "adm"
    mode: 0640
  with_items:
    - debug.log
    - gc.log.0.current
    - system.log
    - cassandra.log
  when: ansible_os_family == "Suse"

